name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:API"
          file: ./API/Dockerfile
          push: true
          tags: your-dockerhub-repo:latest

  deploy:
    needs: docker
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Set up Fly.io CLI
        run: |
          curl -L https://fly.io/install.sh | sh

      - name: Log in to Fly.io
        run: flyctl auth login --auth-token ${{ secrets.FLY_AUTH_TOKEN }}

      - name: Deploy to Fly.io
        run: flyctl deploy --image your-dockerhub-repo:latest